### ISSUE TITLE
Radial search example gets HTTP 500 error

### ISSUE THREAD

**Issue by mguacci** [Chiru/FIWARE-POIDataProvider#3]
Hi,
I'm an italian developer and, at present, I'm working with FIWARE. 
I configure a VM following the steps at "https://forge.fiware.org/plugins/mediawiki/wiki/fiware/index.php/POI_Data_Provider_-_Installation_and_Administration_Guide". 
All works fine until I try to check the radial_search service. When I launch the URL "http://myhostname/poi_dp/radial_search?lat=1&lon=1&category=test_poi" I get 
"NetworkError: 500 Internal Server Error - http://10.11.10.133/poi_dp/radial_search?lat=1&lon=1&category=test_poi", even if on the poi-database the query "SELECT uuid, array_to_string(categories, ',') as categories, thumbnail, st_x(location::geometry) as lon, st_y(location::geometry) as lat, st_astext(geometry) as geometry, timestamp, source_name, source_website, source_id, source_license FROM fw_core WHERE ST_DWithin(location, ST_GeogFromText('POINT(1 1)'), 300) AND categories && '{"test_poi"}' LIMIT 9999" returns a record, and when I test the URL without querystring, it returns the message "'lat' and 'lon' parameters must be specified!" (that proofs that the service is reachable).

Can anybody help me?

Sorry for my English.

Best regards,
Massimiliano

**Comment by mguacci** [comment]
In addition to the previous issue, I report the following log trace from apache log:

[Wed Oct 21 13:24:32 2015] [error] [client 10.100.100.2] PHP Fatal error:  Uncaught exception 'JsonSchema\Exception\JsonDecodingException' with message 'The maximum stack depth has been exceeded' in /var/www/poi_dp/vendor/justinrainbow/json-schema/src/JsonSchema/RefResolver.php:105\nStack trace:\n#0 /var/www/poi_dp/vendor/justinrainbow/json-schema/src/JsonSchema/RefResolver.php(198): JsonSchema\RefResolver->resolve(false, 'file:///var/www...')\n#1 /var/www/poi_dp/vendor/justinrainbow/json-schema/src/JsonSchema/RefResolver.php(128): JsonSchema\RefResolver->resolveProperty(Object(stdClass), 'additionalPrope...', 'file:///var/www...')\n#2 /var/www/poi_dp/vendor/justinrainbow/json-schema/src/JsonSchema/RefResolver.php(198): JsonSchema\RefResolver->resolve(Object(stdClass), 'file:///var/www...')\n#3 /var/www/poi_dp/vendor/justinrainbow/json-schema/src/JsonSchema/RefResolver.php(128): JsonSchema\RefResolver->resolveProperty(Object(stdClass), 'items', 'file:///var/www...')\n#4 /var/www/poi_dp/vendor/justinrainbow/json-schema/src/JsonSchema/RefResolver.php(180): JsonSchema\RefResolver->resolve(Ob in /var/www/poi_dp/vendor/justinrainbow/json-schema/src/JsonSchema/RefResolver.php on line 105

Thank you,
Massimiliano

**Comment by ariokkon** [comment]
The problem is somehow corrected in the current version of POI-DP.
That endless recursion in the JSON validator is caused by the recursive definition of opening time data. It seems to be justinrainbow/json version problem.
Please, try to specify the json-schema version exactly
In OLD installation manual is:
$ php composer.phar require justinrainbow/json-schema:~1.3
try this
$ php composer.phar require justinrainbow/json-schema:1.4.3
